wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1725834484.445911
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      4: 3.10.14
      5: 0.16.0
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
    session_history: code/_session_history.ipynb
